### ISSUE TITLE
optimized path is approximate linear

### ISSUE THREAD

**Issue by zhangzq3054bys** [ishit/L1Stabilizer#5]
hi, thinks for your sharing. now i met a problem. when plotting optimized path, it is approximate linear, and your project is perfect. What is the cause of this?

**Comment by ishit** [comment]
Use this line to tweak the extent of non-linearity:
https://github.com/ishit/L1Stabilizer/blob/1247948ddf651a6d97e0f0c66430b07c1eb2d783/optimizeTransforms.m#L23
And this for error thresholds:
https://github.com/ishit/L1Stabilizer/blob/1247948ddf651a6d97e0f0c66430b07c1eb2d783/optimizeTransforms.m#L36
